- name: implement loops in ansible
  hosts: all
  become: yes
  tasks:
  - name: loop to print list of fruits
    ansible.builtin.debug:
      msg: "The fruit name is {{item}}"
      loop:
        - apple
        - Orange
        - pineapple
        - jackfruit
        - bananana

  - name: print fruits along with quantities
      ansible.builtin.debug:
        msg: "The fruit name is {{item.name}}. quantity is {{item.quantity}}"
        loop:
          - name:apple,quantity:100
          - name:orange,quantity:200